name: Sensio Security Check

on: [push]

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Security Check
        uses: systemli/gh-action-php-security-checker@master
        with:
          args: ./composer.lock
